server:
  port: 8081

spring:
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      ui:
        title: yls—spring-boot监控

  ##注冊服務
  cloud:
    consul:
      discovery:
        #service-name: ${spring.application.name}
        instance-id: yls_project_monitor:8080
      host: localhost
      port: 8500

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS